#!/bin/bash
DRY_RUN=0
function printHelp {
  echo "Utility to run games and applications in separate X on discrete Nvidia graphic card"
  echo "Usage: "
  echo "nvidia-xrun [<options>]"
  echo "Options: "
  echo "  -d    Dry run - prints the final command but does not execute it"
}

function execute {
  if [ $DRY_RUN -eq 1 ]
    then
    echo ">>Dry run. Command: $*"
  else
    eval $*
  fi
}

if [ -z $SU ]; then
   echo "Variable SU no set in env" >&2
   echo "Should be: " >&2
   echo " sudo -> To use sudo; " >&2
   echo " doas -> To use doas; " >&2
   echo " other -> To use other; " >&2
   exit 1
fi

if [[ $EUID -eq 0 ]]; then
   echo "This script must not be run as root" >&2
   exit 1
fi

if [ "$1" == "-d" ]
  then
    DRY_RUN=1
    shift 1
fi

# calculate current VT
LVT=`fgconsole`

# calculate first usable display
XNUM="-1"
SOCK="something"
while [ ! -z "$SOCK" ]
do
  XNUM=$(( $XNUM + 1 ))
  SOCK=$(ls -A -1 /tmp/.X11-unix | grep "X$XNUM" )
done

NEWDISP=":$XNUM"

COMMAND="xinit $HOME/.nvidia-xinitrc -- $NEWDISP vt$LVT -nolisten tcp -br -config nvidia-xorg.conf
-configdir xorg.conf.d"

echo 'Waking up nvidia GPU'
execute "$SU tee /proc/acpi/bbswitch <<<ON"

echo 'Loading nvidia modules'
execute "$SU modprobe nvidia"
execute "$SU modprobe nvidia_drm"

execute $COMMAND

echo 'Unloading nvidia modules'
execute "$SU rmmod nvidia_drm"
execute "$SU rmmod nvidia_modeset"
execute "$SU rmmod nvidia"

echo 'Turning off nvidia GPU'
execute "$SU tee /proc/acpi/bbswitch <<<OFF"
echo -n 'Current state of nvidia GPU: '
execute "cat /proc/acpi/bbswitch"
